### ISSUE TITLE
Support deployment in VPCs where AmazonProvidedDNS is not used

### ISSUE THREAD

**Issue by sclausson** [awslabs/efs-backup#1]
`source/scripts/efs-ec2-backup.sh` uses `dig` to resolve the FQDN of the EFS mount points. In our VPC it is necessary to set the DHCP options to point to internal DNS. Since we query our internal servers, we cannot resolve the IPs of the mount points. If the dig commands were modified in `source/scripts/efs-ec2-backup.sh` so that they queried the VPC DNS ("plus 2 IP"), the EFS Mount Points should be properly resolved.

For example:
`dig @${_vpc_dns} ${_source_efs}.efs.${_region}.amazonaws.com +short`

**Comment by groverlalit** [comment]
Thanks for your input. Your request has been added to the backlog.

**Comment by sclausson** [comment]
@groverlalit https://github.com/awslabs/efs-backup/pull/2 should take care of this.

**Comment by sclausson** [comment]
@groverlalit any update on this one? Shall I rebase PR #2 which now has conflicts since it is so old?

**Comment by oxeedgit** [comment]
@sclausson 

we have the same situation. The DHCP configuration of our VPC setup use only internal DNS Servers. We add the following to the UserData section in efs-to-efs-backup template. This will override the DNS config from DHCP.  

cat <<EOT | sudo tee /etc/resolv.conf
search amazonaws.com
nameserver 169.254.169.253
EOT

AWS maps into every EC2 VM there DNS Servers to 169.254.169.253.

**Comment by gsingh04** [comment]
I agree with @oxeedgit , this seems to be more efficient way to override resolv.conf dns setting and send dns resolution for efs to amazonaws provided dns server. We have added it to our backlog to be released in next iteration.

**Comment by shsenior** [comment]
updated with v1.3.1
