### ISSUE TITLE
Mount is timing out

### ISSUE THREAD

**Issue by kemcadam** [awslabs/efs-backup#15]
1/2 of the nfs mounts has a connection timeout when using this solution. Here is what the logs from the S3 bucket show in relation to mounts.

-- 2018-08-08T21:52:11 -- sudo mkdir /backup
-- 2018-08-08T21:52:11 -- sudo mkdir /mnt/backups
-- 2018-08-08T21:52:11 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.149.2.120:/ /backup
mount.nfs: Connection timed out
mount status for source efs: 32
-- 2018-08-08T21:56:34 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.149.0.220:/ /mnt/backups
mount status for backup efs: 0
-- 2018-08-08T21:56:37 -- ERROR:efs_not_mounted

**Comment by thomasphorton** [comment]
Thanks for the report! What region are you deploying the template in, and what parameters did you provide to the stack?

@gsingh04 what additional information do we need to help debug here?

**Comment by kemcadam** [comment]
Hello, we were in the us-west-2 region and I kept the default parameters, specified a custom VPC and 2 private subnets. Did not change any of the defaults. 

We are thinking now that you have to update the security group on the backup EFS to match the security group of the source EFS. We did not allow the entire VPC CIDR to be open to access the existing EFS as specified in the pre-requisites, which seems to be the issue.

**Comment by thomasphorton** [comment]
Sounds good! Let us know if that doesn't solve your problem.
