### ISSUE TITLE
Make required parameters required

### ISSUE THREAD

**Issue by quiver** [awslabs/efs-backup#16]
CFn templates(both of backup/restore) use parameters and all of them are required according to docs.

But you can deploy them with empty values for some parameters.
Restore's `Restore Log Bucket` parameter is one such example.

Once instances are terminated, there's no way to recover logs.

I will appreciate if you make CFn templates more robust.

**Comment by groverlalit** [comment]
Thanks for your feedback. We have created a PFR for this issue and will make the requested changes in the next release.

**Comment by gsingh04** [comment]
**AWS Backup** a fully managed backup service, now enables you to centrally manage backups for Amazon EFS file systems. We recommend that you evaluate AWS Backup for your specific use case before you use this solution.

**Comment by rccarper** [comment]
With version 1.4, we have made applicable parameters required in the Backup and Restore templates. 
 For viewing logs after EC2 instances have terminated, check out the Log Bucket created by the Backup template.  Thanks again for your feedback!
