### ISSUE TITLE
uuid lib

### ISSUE THREAD

**Issue by marromang** [awslabs/efs-backup#18]
When deploying the cloudformation and testing the lambda I always get the same error message 
`{
  "errorMessage": "module initialization error"
}`

Does anyone know which could be the reason?
Thanks

**Comment by thomasphorton** [comment]
Are you deploying using the CloudFormation Template we host on [AWS Answers](https://aws.amazon.com/answers/infrastructure-management/efs-backup/), or are you modifying source code and deploying your own version?

**Comment by marromang** [comment]
It's the one on the link, the unmodified version

**Comment by groverlalit** [comment]
@marromang  Can you please provide steps to duplicate the issue? Also, can you please share more logs around this error?

Have you considered to open a support case for faster resolution as that will allow you to upload the CloudWatch logs in the support case?
Thanks.

**Comment by marromang** [comment]
We decided to do our own script via data pipeline as we also detected basic syntax errors on the script regarding some spaces that weren't supposed to be there. I'm going to close the issue.
