### ISSUE TITLE
The SSM script could not update the DynamoDB table with backup status, please check the logs in the S3 bucket for the details.

### ISSUE THREAD

**Issue by dviator** [awslabs/efs-backup#19]
After launching the EFS-to-EFS backup solution, it appears to have failed on first run. 

The error message is: "The SSM script could not update the DynamoDB table with backup status, please check the logs in the S3 bucket for the details." 

However, I was unable to find any logs in the S3 bucket after the failure. It appears empty. 

I have double checked the prerequisites listed in the solution, and it appears to me that everything is in order.  Not sure how to further debug. 

I first launched the solution 2 days ago. 
This backup is intended to backup an EFS Cloudstor volume used with Docker4AWS, which created the EFS volume through it's cloudformation stack. Docker4AWS also created the VPC and subnet within which this solution was run. 

Here is the full output of the error message. 

{
"BackupId": "f4436f50",
"BackupPrefix": "/",
"BackupStartTime": "2018-10-17T05:00:07",
"BackupStatus": "Unknown",
"BackupWindow": "180",
"DestinationEfsId": "fs-bf5a9ff5",
"DestinationEfsSize": 6144,
"DestinationPerformanceMode": "generalPurpose",
"ExpireItem": "1547528406",
"InstanceType": "c5.xlarge",
"IntervalTag": "daily",
"Message": "The SSM script could not update the DynamoDB table with backup status, please check the logs in the S3 bucket for the details.",
"RetainPeriod": "14",
"S3BucketSize": "0",
"SourceBurstCreditBalance": 465542823779.75,
"SourceEfsId": "fs-0d637f44",
"SourceEfsSize": 2004533248,
"SourcePerformanceMode": "generalPurpose",
"SourcePermittedThroughput": 104857600
}

Happy to provide additional info as needed.

**Comment by dviator** [comment]
Ended up resolving this. The issue was that the EC2 instance spawned to perform the backup did not have access to the public internet. 

This in turn was due to the fact that it was launched into a VPC which did not automatically assign public IP's to new instances, unlike the default VPC in accounts. 

The fix was adding "AssociatePublicIpAddress: true" to the EC2 portion of the template. It has worked ever since.

**Comment by karthikeayan** [comment]
Shouldn't "AssociatePublicIpAddress: true" be added to the template?

I also faced this issue.
