### ISSUE TITLE
Orchestrator-Role: Member must have length less than or equal to 64

### ISSUE THREAD

**Issue by ab77** [awslabs/efs-backup#23]
In instances where this solution is used in a nested stack configuration, the `RoleName` will almost certainly exceed 64 characters: 

```
HH:MM:SS UTC-0000	CREATE_FAILED	AWS::IAM::Role	OrchestratorRole	1 validation error detected: Value 'Orchestrator-Role-{{some-long-stack-name}}-BackupStack-1T6EMIU72SCD3-us-west-2' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 5a918106-f766-11e8-94af-3578535a537a)
```

Is in imperative that the `OrchestratorRole` specified a `RoleName`, or can it be left empty to be auto-generated?

**Comment by groverlalit** [comment]
If the custom 'RoleName' is removed from the template and it will be auto-generated.

 ... truncated...
  OrchestratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub Orchestrator-Role-${AWS::StackName}-${AWS::Region}
      AssumeRolePolicyDocument:
Version: '2012-10-17'
 ... truncated...

**Comment by groverlalit** [comment]
Thanks for bringing this to our attention. We have created a backlog ticket to track this issue.

**Comment by shsenior** [comment]
updated with v1.3.1
