### ISSUE TITLE
NodeJS8.10 EOL

### ISSUE THREAD

**Issue by kmorrill2** [awslabs/efs-backup#29]
Lambda is retiring the nodejs8.10 runtime as of January 6th: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

The current CF templates use this nodejs version for the AMILookup function.

**Comment by knihit** [comment]
Thank you for reaching out. Updating the Nodejs version is part of our backlog and we are working on it. At this point I am unable to provide a timeline for an updated release, but do watch out for upcoming releases for this solution

**Comment by beomseoklee** [comment]
We have launched the new version which are using the latest Lambda runtime.
