### ISSUE TITLE
Problems with the restore script

### ISSUE THREAD

**Issue by evansj** [awslabs/efs-backup#5]
I found the restore process very confusing with the field names (/Source EFS Id/ and /Backup EFS Id/), and I also couldn't get it to work due to the EC2 instance not having a Security Group which our existing EFS instances required.

I have addressed these issues in PR #4.

**Comment by evansj** [comment]
This repo looks pretty dead. :-(

**Comment by gsingh04** [comment]
apologies for the delay, we are addressing the concerns from PR #4 . expect an update today.

**Comment by stevemorad** [comment]
v1.1 changes pushed to GitHub and to published solution
