### ISSUE TITLE
Read/Write Capacity Units for DDB

### ISSUE THREAD

**Issue by waynerobinson** [awslabs/efs-backup#8]
Is the RCU/WCU setting of 5 for DynamoDB a little high for this implementation?

Especially as the table is effectively per-stack and the system will only run at most daily with a handful of read/writes at the beginning/end of the backup execution.

Surely an RCU/WCU set to 1 is more than enough, especially with the burst capacity that DDB has.

**Comment by thomasphorton** [comment]
Great question- we'll take a look at this and see about setting different defaults. In the mean time, you can adjust these in the CloudFormation template on lines [360](https://github.com/awslabs/efs-backup/blob/master/deployment/efs-to-efs-backup.template#L360) and [361](https://github.com/awslabs/efs-backup/blob/master/deployment/efs-to-efs-backup.template#L361).

Thank you for pointing this out!

**Comment by gsingh04** [comment]
we have released efs-backup v1.3, please close the issue or feel free to update here if you face any concerns
https://aws.amazon.com/answers/infrastructure-management/efs-backup/
